### ISSUE TITLE
Idea for accessibility: Adjust colors and/or thicken/texture the antenna feed line

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [ChrisAdderley/NearFutureExploration#15]
It would increase accessibility to have the line change thickness and/or texture (dotted vs. dashed) as well as color.

I have normal color vision, but I've played around a bit with GIMP's color-deficient vision filter to see if there's a way to improve that just by adjusting the colors (since that's much easier), and it looks like having goodColor be (0.6, 1, 0.6), i.e. a lighter green, will do the trick.

**Comment by ChrisAdderley** [comment]
Will be changed to cyan (should work according to a chart I found) in 1.0.3.

**Comment by ChrisAdderley** [comment]
This should be fixed in 1.0.3 now.
