### ISSUE TITLE
PLTO model rotation and other probe core indicator labels

### ISSUE THREAD

**Issue by GHrynk** [ChrisAdderley/NearFutureExploration#16]
The PLTO model appears to be rotated 90 deg from what would be the intuitive "zero" rotation point.  Requesting axis re-orientation so that the flat side with the "PLTO" label is opposite the VAB flag, per standard KSP command pod default rotation convention. 

Most of the new cores also appear to have their labels opposite of the standard positioning convention.  This makes it difficult at a glance to figure out, short of initiating a powered rotation in flight, which side of the probe core is the "zero" rotation reference point.

**Comment by ChrisAdderley** [comment]
This is not really feasible as it would break all existing craft using those parts. I have added a poll on the forums.

**Comment by ChrisAdderley** [comment]
This should be fixed in 1.0.3 now.
