### ISSUE TITLE
Feeder Reflector Indicator Line toggle

### ISSUE THREAD

**Issue by GHrynk** [ChrisAdderley/NearFutureExploration#17]
The indicator line for the antenna feed-to-reflection defaults to "on".  Even after turning it off, adding another antenna brings it back up again, adding clutter to the VAB.  Can we get a global Toggle so the indicator stays in the last state (on or off) until that state is deliberately changed by the user?

**Comment by ChrisAdderley** [comment]
Will be set to off by default in 1.0.3.

**Comment by ChrisAdderley** [comment]
This should be fixed in 1.0.3 now.
