### ISSUE TITLE
NullReferenceException with CommNet Constellation

### ISSUE THREAD

**Issue by gholms** [ChrisAdderley/NearFutureExploration#22]
When CommNet Constellation is used with NFX all antennas, both stock and from this mod, lack the button one would normally use to set their frequencies, and attempting to set their frequencies using the dialog for the whole vessel throws the same sort of NullReferenceExceptions as those in issue #18.  It looks like you're using a blacklisting approach to handle compatibility with the patches to stock antennas, so while adding CNC to those blacklists would probably resolve the issue for stock antennas, would that make any difference to the ones from NFX?

**Comment by ChrisAdderley** [comment]
I don't think it's required. Check the conversation here: https://forum.kerbalspaceprogram.com/index.php?/topic/158851-181-commnet-constellation-v151-8-december-2019/&do=findComment&comment=3737057
We're working on resolving the issue and it will probably be fixed by the next CNC release.

**Comment by gholms** [comment]
This seems to be fixed in CNC's master branch
