### ISSUE TITLE
No antenna feed

### ISSUE THREAD

**Issue by Gyrofish** [ChrisAdderley/NearFutureExploration#27]
In 1.0.6 option to toggle feeder line in VAB is not there, in lower versions line does not appear when toggled. In all cases reflectors do not combine with feeders, "reflector bonus" in flight stay blank even if pointing to the deployed reflector. What could be the issue there?

**Comment by ChrisAdderley** [comment]
Do you have RemoteTech? This mod is not compatible with Remote Tech.

**Comment by Gyrofish** [comment]
> 
> 
> Do you have RemoteTech? This mod is not compatible with Remote Tech.

I do not, but i do have a big mod list. Nothing about comm. network though. Engines, parts, USI life support and consctruction, KAS, KIS, all of Near Future, SCANsat and Probes Before Crew.

What are the triggers that disable features when RemoteTech is detected? Can it trip on auxilliary mods like libraries?

**Comment by ChrisAdderley** [comment]
Not generally. There are two disable points at the moment - RealAntennas and RemoteTech.
There is a known issue in the community with another mod called ResearchBodies which has a very bad error in its configs that causes other mods to think RemoteTech is installed. Do you have that mod?

If not, I'm going to need actual information about your install. 
* Mod list
* KSP logfile
* ModuleManager cache file

**Comment by Gyrofish** [comment]
ResearchBodies is installed, removing it resolved the issue. Thanks!

**Comment by ChrisAdderley** [comment]
Great. If you still want RB, see here: https://github.com/JPLRepo/ResearchBodies/issues/48. There are instructions for how to fix the RB bug so it doesn't break everything.
