### ISSUE TITLE
MLT-R2 Tank has negative mass when configured with LH2 or LH2O

### ISSUE THREAD

**Issue by Hieywiey** [ChrisAdderley/NearFutureExploration#30]
Tank dry has a mass of -3kg for both, full load of LH2 in either config has insufficient mass to bring this above 0, Oxidizer in LH2O config can do this as the full load weighs 4kg.
<img width="332" alt="Screen Shot 2020-05-20 at 12 19 56 PM" src="https://user-images.githubusercontent.com/6867750/82477215-c9d15d00-9a94-11ea-902b-de207f9233f4.png">
<img width="336" alt="Screen Shot 2020-05-20 at 12 20 19 PM" src="https://user-images.githubusercontent.com/6867750/82477218-cb028a00-9a94-11ea-95b1-d857521cf68b.png">
<img width="322" alt="Screen Shot 2020-05-20 at 12 20 42 PM" src="https://user-images.githubusercontent.com/6867750/82477233-cfc73e00-9a94-11ea-8f7f-85b33bf9f3f9.png">

**Comment by ChrisAdderley** [comment]
Released.
