### ISSUE TITLE
ModuleAntennaFeed.FixedUdpate() NullReferenceException

### ISSUE THREAD

**Issue by E3FxGaming** [ChrisAdderley/NearFutureExploration#34]
KSP Version: 1.10.1.2939
Near Future Exploration version 1.0.9

This is a description for bug that happens with all antennas that have the "Antenna Feed" module.

When those antennas are deployed and are torn off during reentry, KSP starts stuttering a lot.

This is due to hundreds of exceptions being thrown. In the KSP log, it looks like this:

    [LOG 11:16:10.738] AX-30 High Gain Micro-Antenna: Antenna broken by aero forces.

    [EXC 11:16:11.168] NullReferenceException

    UnityEngine.LineRenderer.SetPosition (System.Int32 index, UnityEngine.Vector3 position) (at <7d9ec060e791409ab3eb85c61e312ed6>:0)

    VisualDebugUtils.DebugLine.AdjustSize (System.Single size) (at <6926964e837c4edfbee9d6c5a2953bcf>:0)

    NearFutureExploration.ModuleAntennaFeed.FixedUpdate () (at <6926964e837c4edfbee9d6c5a2953bcf>:0)

    UnityEngine.DebugLogHandler:LogException(Exception, Object)

    ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)

    UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)`

The NullReferenceException stacktrace repeats itself over and over until the vessel isn't loaded anymore (in my test cases I landed the vessel and only after clicking "recover vessel" the game FPS would improve again).

As far as I can tell from the stacktrace, the exception throwing code can be found here: https://github.com/ChrisAdderley/NearFutureExploration/blob/06b2bae77dcaa4b4593e1ed90a1254a018418b79/Source/ModuleAntennaFeed.cs#L148-L194

I know too little about the code to pinpoint what exactly is throwing the exception.

Steps to easily reproduce the problem:

1. Build a test vessel. Doesn't have to be anything fancy, you can use cheats to get it into Kerbin orbit, just needs to have enough delta-V to get  a suborbital trajectory. My test vessel:

![image](https://user-images.githubusercontent.com/8276268/89175025-2a960f00-d587-11ea-9c7b-40345a9341a8.png)

^ My test craft. All stock (from top to bottom: parachute, capsule, heat shield, decoupler, battery, fuel tank, reaction wheel and skipper engine) + 2 times the "RA-0-8 Relay Antenna" added by Near Future Exploration (antennas that have the "Antenna Feed" module).

2. Cheat it into orbit, make sure the antennas are deployed and de-orbit the vessel by burning retrograde until the map shows that the craft will dive deep into the atmosphere.

3. Time warp till atmospheric entry, then you can either watch what is happening in real time or use physical time warp to speed things up.

4. Once the deployed antennas break the exception throwing will start.

Note that it has to be aero forces that break the antennas. I tried recreating the problem on the ground by pointing an engine at antennas and heating them up, but this did not cause the exception throwing.

Installed mods during my tests (no mods that have anything to do with antennas, basically just MechJeb 2, GravityTurn Continued, and Near Future Exploration, plus the dependencies of the 3 aforementioned mods):

- B9 Part Switch (B9PartSwitch v2.17.0)
- ClickThrough Blocker (ClickThroughBlocker 1:0.1.10.11)
- GravityTurn Continued (GravityTurnContinued 3:1.8.1)
- MechJeb 2 (MechJeb2 2.10.0.0)
- Module Manager (ModuleManager 4.1.4)
- Near Future Exploration (NearFutureExploration 1.0.9)
- Toolbar Controller (ToolbarController 1:0.1.9.4)
- Zero MiniAVC (ZeroMiniAVC 1:1.1.0.1)

**Comment by ChrisAdderley** [comment]
Thanks for the detailed bug report. This will be fixed in the next version, which will be released whenever Spacedock stops having problems.
