### ISSUE TITLE
KSP struggles to load the mod

### ISSUE THREAD

**Issue by nally85** [ChrisAdderley/NearFutureExploration#36]
Hi,

I have just got back into KSP and have used your mods before.

I have installed via CKAN with a number of you other mods. I have the other mods requried B9, etc...

But when I try to load the game it stops at NearFutureExploration/Parts/FuelTank/nfex-fueltank-radial-small-1/nfex-fueltank-radial-small-1.

If I uninstall Near future exploration the game fails to load as it seams to be looking for a part that was in near future exploration.

I have attached a screenshot of the loading screen and my log file. 

Any ideas?

Many thanks and kind regards

Liam[
[KSP.log](https://github.com/ChrisAdderley/NearFutureExploration/files/5251690/KSP.log)
![Untitled picture](https://user-images.githubusercontent.com/71594694/93711905-d00e3d80-fb49-11ea-9162-57e74b33eb2b.png)

](url)

**Comment by ChrisAdderley** [comment]
You appear to have CryoTanks installed without the Community Resource Pack. That is not a dependency for NFEx, but it is a dependency for CT, and the presence of CT enables special features of NFEx that assume CRP exists.
Long story short, install CRP to have all CT dependencies, this should resolve things

**Comment by nally85** [comment]
Thanks Chris followed your advice and now i am sorted.

Kind regards
